/* Lesson 4.1.1 - Macroeconomic aims */
window.IGCSE = window.IGCSE || {};

IGCSE.lesson = {
  meta: {
    code: '4.1.1',
    unit: 'Unit 4 - Government and the macroeconomy',
    title: 'Macroeconomic aims - Cambridge IGCSE Economics 0455',
    lessonLabel: 'Macroeconomic aims',
    courseLabel: 'Cambridge IGCSE Economics 0455',
  },

  slides: [
    {
      type: 'hero',
      eyebrow: 'Cambridge IGCSE Economics 0455',
      title: 'Macroeconomic aims',
      subtitle: '4.1.1',
      kicker: 'What is the government trying to achieve for the whole economy?',
    },
    {
      type: 'outcomes',
      eyebrow: 'Lesson objectives',
      title: 'By the end, you can',
      bullets: [
        'Identify the six main macroeconomic aims.',
        'Explain why each aim matters for an economy.',
        'Analyse conflicts between aims using clear cause-and-effect chains.',
      ],
      footer: 'Success looks like: aim named, reason explained, conflict evaluated.',
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Starter',
      title: 'Choose the priority',
      question: 'A country has rising GDP, rising pollution, low unemployment and fast inflation. Which aim should the government prioritise first?',
      choices: ['Economic growth', 'Stable prices', 'Environmental sustainability', 'Low unemployment'],
      prompt: 'Give one reason and one possible cost of your choice.',
      visual: 'abstract',
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'cards',
      eyebrow: 'Six aims',
      title: 'What governments try to achieve',
      lead: 'Macroeconomic aims focus on the performance of the whole economy.',
      cards: [
        ['Economic growth', 'increase real GDP and output'],
        ['Full employment', 'keep unemployment low'],
        ['Stable prices', 'keep inflation low and predictable'],
        ['Balance of payments stability', 'avoid persistent external imbalances'],
        ['Redistribution of income', 'reduce excessive income inequality'],
        ['Environmental sustainability', 'protect resources and reduce damage'],
      ],
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'flow',
      eyebrow: 'Why it matters',
      title: 'Growth can raise living standards',
      nodes: [['higher real GDP', 'more goods and services', 'higher incomes may follow', 'living standards may improve']],
      footer: 'Evaluation: growth does not guarantee equal benefits or lower pollution.',
      visual: 'demandUp',
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Why it matters',
      title: 'Stable prices protect confidence',
      nodes: [['low and stable inflation', 'money keeps its purchasing power', 'firms can plan', 'investment may increase']],
      footer: 'High inflation creates uncertainty and can reduce real incomes.',
      visual: 'demandDown',
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'cards',
      eyebrow: 'Conflicts',
      title: 'Aims can clash',
      lead: 'Good answers recognise trade-offs rather than assuming every aim improves together.',
      cards: [
        ['Employment vs inflation', 'more demand may create jobs but raise prices'],
        ['Growth vs sustainability', 'more output may use more resources and create pollution'],
        ['Employment vs balance of payments', 'higher incomes may increase spending on imports'],
      ],
      footer: 'Use cautious language: may, could, depends on spare capacity.',
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title: 'Which conflict is shown?',
      question: 'A government increases spending to create jobs. Consumers then buy more imported goods.',
      choices: ['Employment vs balance of payments stability', 'Growth vs sustainability', 'Stable prices vs redistribution'],
      prompt: 'Explain the chain in one sentence.',
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'exam',
      eyebrow: 'Exam practice',
      title: 'Explain a conflict',
      question: 'Explain why economic growth may conflict with environmental sustainability.',
      keywords: ['more output', 'resource use', 'pollution', 'sustainability'],
      prompt: 'Write a linked chain and include one judgement word such as "may".',
      visual: 'flowArrows',
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'answer',
      eyebrow: 'Exit check',
      title: 'Three retrieval prompts',
      steps: [
        ['1', 'Name two macroeconomic aims.'],
        ['2', 'State one reason low inflation is useful.'],
        ['3', 'Explain one conflict between two aims.'],
      ],
      cue: 'Answer without notes before leaving.',
      partialReview: ['.steps > .step', '.prompt'],
    },
  ],
};
