/* ============================================================
   Lesson 4.2 - Fiscal policy
   Cambridge IGCSE Economics 0455 - Unit 4: Government and the macroeconomy

   Syllabus source:
   ../../../references/igcse-economics-syllabus-2027-2029.md

   Pacing note:
   Keep each slide to one teaching move and tie each policy effect back to
   the macroeconomic aims taught in 4.1.1.
   ============================================================ */

window.IGCSE = window.IGCSE || {};

const localPhoto = (file, alt, credit) => ({
  type: 'photo',
  src: `../../../assets/images/fiscal-policy/${file}`,
  alt,
  caption: alt.replace(/\.$/, ''),
  credit,
});

const factPhoto = (file, caption, credit, source) => ({
  type: 'photo',
  src: `../../../assets/images/fiscal-policy/facts/${file}`,
  alt: caption,
  caption,
  credit,
  source,
});

const photos = {
  budgetMeeting: localPhoto(
    'budget-meeting-with-congress.jpg',
    'Government officials seated around a table during budget negotiations.',
    'Wikimedia Commons / Robert McNeely'
  ),
  budgetHearing: localPhoto(
    'house-budget-committee-meeting-2020-01-15.jpg',
    'A legislative budget committee meeting in progress.',
    'Wikimedia Commons / House Budget Committee Democrats'
  ),
  classroom: localPhoto(
    'students-in-a-classroom.jpg',
    'Students working at desks in a classroom.',
    'Wikimedia Commons / Ente75'
  ),
  healthcare: localPhoto(
    'doctors-and-nurses-at-the-3rd-field-hospital.jpg',
    'Doctors and nurses standing together in a hospital.',
    'Wikimedia Commons / Defense VI Records Center'
  ),
  defence: localPhoto(
    'defence-officials-meeting.jpg',
    'Defence officials seated for a formal bilateral meeting.',
    'Wikimedia Commons / U.S. Secretary of Defense'
  ),
  roadwork: localPhoto(
    'going-to-the-sun-road-paving.jpg',
    'A road construction crew paving a mountain road.',
    'Wikimedia Commons / U.S. Dept. of Transportation'
  ),
  industry: localPhoto(
    'national-semiconductor-factory.jpg',
    'The exterior of a semiconductor factory.',
    'Wikimedia Commons / william craig'
  ),
  socialSecurity: localPhoto(
    'signing-of-the-social-security-act.jpg',
    'President Roosevelt signing the Social Security Act.',
    'Wikimedia Commons / National Archives'
  ),
  shopping: localPhoto(
    'shopping-carts-in-a-grocery-store.jpg',
    'Rows of shopping carts inside a grocery store.',
    'Wikimedia Commons / Visitor7'
  ),
  taxForms: localPhoto(
    'tax-forms.jpg',
    'Printed tax forms laid out on a table.',
    'Wikimedia Commons / Kalamazoo Public Library'
  ),
  tobacco: localPhoto(
    'tobacco-cigarette-pack.jpg',
    'A cigarette pack photographed on a table.',
    'Wikimedia Commons / Lindsay Fox'
  ),
  pollution: localPhoto(
    'smokestack-in-detroit.jpg',
    'A smokestack rising from an industrial plant.',
    'Wikimedia Commons / Gyre'
  ),
  port: localPhoto(
    'cargo-containers.jpg',
    'Stacks of cargo containers at a waterfront port.',
    'Wikimedia Commons / Roy Luck'
  ),
  inflation: localPhoto(
    'meat-inflation-in-the-united-states.jpg',
    'A grocery shelf with posted meat prices.',
    'Wikimedia Commons / Wikideas1'
  ),
};

const factPhotos = {
  ukBudget: factPhoto(
    'uk-budget-rachel-reeves.jpg',
    'Rachel Reeves official portrait',
    'Wikimedia Commons / Chris McAndrew',
    'https://commons.wikimedia.org/wiki/File:Official_portrait_of_Rachel_Reeves_crop_2.jpg'
  ),
  finlandEducation: factPhoto(
    'finland-vantaankoski-classroom.jpg',
    'Vantaankoski school classroom',
    'Wikimedia Commons / Leo-setä',
    'https://commons.wikimedia.org/wiki/File:Elementary_school_classroom_in_Vantaankoski_school_in_Vantaa,_Finland,_2010.jpg'
  ),
  usSemiconductors: factPhoto(
    'us-intel-d1x-fab.png',
    'Intel D1X semiconductor fab',
    'Wikimedia Commons / Intel Free Press',
    'https://commons.wikimedia.org/wiki/File:Intel_D1X_Development_Fab_Hillsboro_Oregon.png'
  ),
  denmarkTax: factPhoto(
    'denmark-ministry-taxation.jpg',
    'Danish Ministry of Taxation',
    'Wikimedia Commons / Bjoertvedt',
    'https://commons.wikimedia.org/wiki/File:Copenhagen_Skatteministeriet_IMG_5647.jpg'
  ),
  philippinesTobacco: factPhoto(
    'philippines-tobacco-warning-labels.jpg',
    'Philippine tobacco warning labels',
    'Wikimedia Commons / Government of the Philippines',
    'https://commons.wikimedia.org/wiki/File:PH_tobacco_packaging_graphic_warning_labels.jpg'
  ),
  ukSugar: factPhoto(
    'uk-soft-drink-shelf.jpg',
    'Soft drinks on supermarket shelves',
    'Wikimedia Commons',
    'https://commons.wikimedia.org/wiki/File:Soft_drink_shelf.JPG'
  ),
  euCbam: factPhoto(
    'netherlands-rotterdam-container-terminal.jpg',
    'Port of Rotterdam container terminal',
    'Wikimedia Commons / AgainErick',
    'https://commons.wikimedia.org/wiki/File:Waalhaven_pier_6_-_Port_of_Rotterdam_-_container_terminal_and_cranes.jpg'
  ),
  swedenCarbon: factPhoto(
    'sweden-hammarbyverket.jpg',
    'Hammarbyverket energy plant',
    'Wikimedia Commons / Holger.Ellgaard',
    'https://commons.wikimedia.org/wiki/File:Hammarbyverket_2008.jpg'
  ),
  singaporeBudget: factPhoto(
    'singapore-budget-2024-thumbnail.jpg',
    'Singapore Budget 2024 video thumbnail',
    'YouTube / Singapore MOF',
    'https://www.mof.gov.sg/budget-archives/budget-2024/'
  ),
};

IGCSE.lesson = {
  meta: {
    code:         '4.2',
    unit:         'Unit 4 - Government and the macroeconomy',
    title:        'Fiscal policy - Cambridge IGCSE Economics 0455',
    lessonLabel:  'Fiscal policy',
    courseLabel:  'Cambridge IGCSE Economics 0455',
    creatorLabel: 'Created by Samuel Oehler-Huang, Suzhou Foreign Language School',
  },

  slides: [
    {
      type: 'hero',
      eyebrow:  'Lesson overview',
      title:    'Fiscal policy',
      subtitle: 'Government spending and taxation',
      kicker:   'How can a budget help meet macroeconomic aims?',
    },
    {
      type: 'outcomes',
      eyebrow: 'Objectives',
      title:   'By the end, you can',
      bullets: [
        'Calculate deficits and surpluses.',
        'Explain spending and taxation.',
        'Classify tax types.',
        'Link fiscal policy to macro aims.',
      ],
    },
    {
      type: 'roadmap',
      eyebrow: 'Lesson overview',
      title:   'Today\'s route',
      items: [
        ['4.2.1', 'Budget', 'revenue, expenditure, deficit, surplus'],
        ['4.2.2', 'Spending', 'main areas, reasons and effects'],
        ['4.2.3', 'Taxation', 'reasons and types of taxes'],
        ['4.2.4-4.2.6', 'Fiscal policy', 'measures and effects on macro aims'],
      ],
      visual: photos.budgetHearing,
    },
    {
      type: 'quiz',
      eyebrow: 'Starter',
      title:   'You control the budget',
      question: 'Growth is slowing, unemployment is rising, prices are still increasing, and pollution is high. What should the government prioritise?',
      choices: [
        'Economic growth',
        'Low unemployment',
        'Low inflation',
        'Environmental sustainability',
      ],
      prompt: 'Choose one aim, then name the likely trade-off.',
      visual: photos.budgetMeeting,
    },
    {
      type: 'discussion',
      eyebrow: 'Starter',
      title:   'Trade-offs',
      question: 'What should a government do first when it cannot achieve every aim at once?',
      zh: '当政府无法同时实现所有目标时，应该先做什么？',
      visual: photos.budgetMeeting,
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Government budget',
      subtitle: 'Revenue and expenditure decide whether there is a deficit or surplus.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Public money',
      question: 'What should happen if a government spends more than it receives?',
      zh: '如果政府支出超过收入，应该怎么办？',
      visual: photos.budgetHearing,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Budget balance',
      term:    'government budget',
      definition: 'A government budget is a plan for government revenue and government expenditure.',
      formula: 'Budget balance = government revenue - government expenditure',
      examples: ['negative balance = deficit', 'positive balance = surplus'],
      visual:  photos.budgetMeeting,
      partialReview: ['.termBox', '.formula', '.choices > .choice'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇬🇧',
          country: 'United Kingdom',
          fact: 'UK public borrowing was GBP 131.1 billion (about RMB 1.2 trillion) in 2023/24.',
          zh: '2023/24财年，英国公共借款为1311亿英镑（约1.2万亿元人民币）。',
          source: 'Source: UK ONS; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China planned a RMB 4.06 trillion budget deficit in 2024, equal to 3% of GDP.',
          zh: '中国2024年安排预算赤字4.06万亿元人民币，相当于GDP的3%。',
          source: 'Source: 2024 Government Work Report.',
        },
      },
      visual: factPhotos.ukBudget,
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title:   'Deficit or surplus?',
      question: 'Government revenue = $420m. Government expenditure = $510m.',
      choices: ['$90m surplus', '$90m deficit', '$930m deficit'],
      prompt:  'Calculate revenue - expenditure.',
      visual:  photos.taxForms,
    },
    {
      type: 'answer',
      eyebrow: 'Check',
      title:   'Answer',
      answer:  '$90m deficit',
      body:    '$420m - $510m = -$90m. A deficit occurs because spending is greater than revenue.',
      visual:  photos.budgetMeeting,
      partialReview: ['.answerBox'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Deficit or surplus?',
      leftTitle:  'Budget deficit',
      left:  ['government spending exceeds government revenue', 'may require borrowing'],
      rightTitle: 'Budget surplus',
      right: ['government revenue exceeds government spending', 'may reduce borrowing or debt'],
      prompt: 'A balanced budget means revenue equals expenditure.',
      visual: photos.budgetHearing,
      partialReview: ['.splitCols > .card', '.prompt'],
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Government spending',
      subtitle: 'Main areas of spending have different macroeconomic effects.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Priorities',
      question: 'Which area of government spending should receive more money first?',
      zh: '政府支出的哪个领域应该最先获得更多资金？',
      visual: photos.budgetHearing,
    },
    {
      type: 'cards',
      eyebrow: 'Learn',
      title:   'Main areas of spending',
      cards: [
        ['Education', 'schools and training'],
        ['Healthcare', 'hospitals and public health'],
        ['Infrastructure', 'transport and digital networks'],
        ['Welfare', 'benefits and pensions'],
        ['Defence', 'national security'],
        ['Industry support', 'subsidies and research'],
      ],
      visual: photos.budgetHearing,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇫🇮',
          country: 'Finland',
          fact: 'Finland’s government education spending was 6.38% of GDP in 2022.',
          zh: '2022年，芬兰政府教育支出占GDP的6.38%。',
          source: 'Source: World Bank, based on UNESCO UIS data.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China spent RMB 6.4595 trillion on education in 2023.',
          zh: '2023年，中国教育经费总投入达到6.4595万亿元人民币。',
          source: 'Source: China Ministry of Education.',
        },
      },
      visual: factPhotos.finlandEducation,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Why spend?',
      question: 'Why might markets fail to provide enough education, healthcare or infrastructure?',
      zh: '为什么市场可能无法提供足够的教育、医疗或基础设施？',
      visual: photos.classroom,
    },
    {
      type: 'cards',
      eyebrow: 'Learn',
      title:   'Why governments spend',
      cards: [
        ['Merit goods', 'education, healthcare', '1'],
        ['Public goods', 'defence', '2'],
        ['Infrastructure', 'roads, rail, ports', '3'],
        ['Key industries', 'subsidies, R&D', '4'],
        ['Inequality', 'benefits, pensions', '5'],
        ['Macroeconomy', 'demand, inflation', '6'],
      ],
      visual: photos.budgetHearing,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Education and healthcare',
      question: 'Why might a person consume too little education or healthcare if they must pay the full price?',
      zh: '如果必须支付全部价格，为什么人们可能消费太少的教育或医疗？',
      visual: photos.classroom,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '1. Provide merit goods',
      question: 'Education and healthcare may be underprovided if people have to pay the full price.',
      nodes: [['government funds schools or hospitals', 'more people can access them', 'skills and health improve', 'productivity may rise']],
      footer: 'Exam link: merit goods can improve living standards and long-run growth.',
      visual: photos.classroom,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Free rider problem',
      question: 'Why is defence difficult to sell only to people who pay for it?',
      zh: '为什么国防很难只卖给付费的人？',
      visual: photos.defence,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '2. Provide public goods',
      question: 'Some goods would not be provided by private firms because people can benefit without paying directly.',
      nodes: [['government funds defence', 'the country is protected', 'people and firms face less risk', 'economic activity is protected']],
      footer: 'Exam link: public goods create benefits that markets may not provide.',
      visual: photos.defence,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Roads, rail and ports',
      question: 'How can a better road or railway help firms produce more?',
      zh: '更好的公路或铁路如何帮助企业生产更多？',
      visual: photos.roadwork,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '3. Invest in infrastructure',
      nodes: [['more infrastructure spending', 'lower transport costs', 'firms may produce more', 'real GDP may rise']],
      footer: 'This links spending to economic growth.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'The government builds a new railway between factories and a port. Which reason for spending is most direct?',
      choices: [
        'Provide a public good',
        'Invest in infrastructure',
        'Reduce inequality',
      ],
      prompt: 'Say the answer, then add one likely effect on firms.',
      visual: photos.roadwork,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Picking winners',
      question: 'Should a government support an industry if it is important for future jobs?',
      zh: '如果某个产业对未来就业很重要，政府应该支持它吗？',
      visual: photos.industry,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇺🇸',
          country: 'United States',
          fact: 'The U.S. CHIPS Act offered $52.7 billion (about RMB 380 billion) for semiconductors.',
          zh: '《芯片法案》为美国半导体产业提供527亿美元（约3800亿元人民币）。',
          source: 'Source: NIST; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China’s Big Fund III had RMB 344 billion registered capital.',
          zh: '中国大基金三期注册资本为3440亿元人民币。',
          source: 'Source: Gov.cn.',
        },
      },
      visual: factPhotos.usSemiconductors,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '4. Support key industries',
      question: 'Governments may support industries that are important for jobs, exports or future technology.',
      nodes: [['subsidy for a key industry', 'firms face lower costs', 'investment or R&D may rise', 'competitiveness may improve']],
      footer: 'Evaluation: subsidies have an opportunity cost and may protect inefficient firms.',
      visual: photos.industry,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Welfare support',
      question: 'How much responsibility should a government take for reducing poverty?',
      zh: '政府在减少贫困方面应该承担多大责任？',
      visual: photos.socialSecurity,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '5. Reduce inequality',
      nodes: [['higher welfare spending', 'poorer households receive support', 'income inequality may fall']],
      footer: 'Add a cost: the government may need higher taxes or borrowing.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Managing demand',
      question: 'Should a government spend more when unemployment is rising?',
      zh: '当失业率上升时，政府应该增加支出吗？',
      visual: photos.budgetMeeting,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '6. Manage the macroeconomy',
      question: 'Government spending can be changed to influence total demand.',
      nodes: [['higher government spending', 'total demand rises', 'firms may increase output', 'growth and employment may rise']],
      footer: 'Evaluation: demand may rise too much and create inflationary pressure.',
      visual: photos.budgetMeeting,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'The government increases unemployment benefits during a downturn. Which reason fits best?',
      choices: [
        'Reduce inequality',
        'Support key industries',
        'Provide public goods',
      ],
      prompt: 'Now name one possible opportunity cost.',
      visual: photos.socialSecurity,
    },
    {
      type: 'quiz',
      eyebrow: 'Apply',
      question: 'Which spending decision most directly supports environmental sustainability?',
      choices: [
        'Build cleaner public transport',
        'Increase debt-interest payments',
        'Cut education spending',
      ],
      prompt: 'Now add one possible opportunity cost.',
      visual: photos.pollution,
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Taxation',
      subtitle: 'Taxes raise revenue, change behaviour and influence demand.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Every receipt is a policy choice',
      question: 'Which taxes do you already know?',
      zh: '你已经知道哪些税？',
      visual: photos.shopping,
    },
    {
      type: 'outcomes',
      eyebrow: 'Objectives',
      title:   'By the end of the taxation lesson, you can',
      bullets: [
        'Explain reasons for taxation.',
        'Distinguish between direct and indirect tax.',
        'Distinguish between proportional, progressive and regressive tax.',
        'Use real examples.',
      ],
      visual: photos.taxForms,
    },
    {
      type: 'quiz',
      eyebrow: 'Starter',
      title:   'What do you already know?',
      question: 'Which statement is most accurate?',
      choices: [
        'All taxes are paid directly by households to the government.',
        'Some taxes are paid on income; others are paid when goods and services are bought.',
        'A tax can only raise revenue and cannot change behaviour.',
      ],
      prompt: 'Choose one, then correct one wrong statement.',
      visual: photos.taxForms,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇩🇰',
          country: 'Denmark',
          fact: 'Denmark’s tax revenue was 45.2% of GDP in 2024.',
          zh: '2024年，丹麦税收收入占GDP的45.2%。',
          source: 'Source: OECD Revenue Statistics 2025.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China’s tax revenue was 20.4% of GDP in 2023.',
          zh: '2023年，中国税收收入占GDP的20.4%。',
          source: 'Source: OECD Revenue Statistics in Asia and the Pacific 2025.',
        },
      },
      visual: factPhotos.denmarkTax,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '1. Raise revenue',
      nodes: [['government charges taxes', 'revenue rises', 'public services can be funded']],
      footer: 'Example: income tax can help fund education and healthcare.',
      visual: photos.taxForms,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '2. Reduce demerit goods',
      nodes: [['tax on cigarettes', 'price rises', 'quantity demanded may fall', 'health costs may fall']],
      footer: 'Evaluation: demand may be price inelastic.',
      visual: photos.tobacco,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇦🇺',
          country: 'Australia',
          fact: 'Australia’s cigarette excise tax was AUD 1.40312 per stick (about RMB 6.7) in March 2025.',
          zh: '2025年3月，澳大利亚香烟消费税为每支1.40312澳元（约6.7元人民币）。',
          source: 'Source: Australian Taxation Office; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China’s Class A cigarettes face a 56% production excise tax plus 11% wholesale excise tax.',
          zh: '中国甲类卷烟征收56%生产环节消费税，另加11%批发环节消费税。',
          source: 'Source: China consumption tax rate table.',
        },
      },
      visual: factPhotos.philippinesTobacco,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '3. Reduce imports',
      nodes: [['tariff on imports', 'import prices rise', 'consumers may buy fewer imports', 'domestic firms may sell more']],
      footer: 'Evaluation: other countries may retaliate.',
      visual: photos.port,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'A government increases tax on alcohol. Which reason for taxation is most direct?',
      choices: [
        'Raise revenue only',
        'Reduce consumption of a demerit good',
        'Reduce imports',
      ],
      prompt: 'Add one reason why the effect may be limited.',
      visual: photos.tobacco,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '4. Redistribute income',
      nodes: [['higher taxes on high incomes', 'government revenue rises', 'welfare can be funded', 'inequality may fall']],
      footer: 'Progressive taxes are usually linked most directly to redistribution.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '5. Influence demand',
      nodes: [['higher income tax', 'disposable income falls', 'consumer spending may fall', 'inflationary pressure may fall']],
      footer: 'This may conflict with growth and employment.',
      visual: photos.inflation,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '6. Encourage sustainability',
      nodes: [['pollution tax', 'firms face higher costs for polluting', 'cleaner methods become more attractive']],
      footer: 'Evaluate: firms may pass higher costs to consumers.',
      visual: photos.pollution,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'A pollution tax raises money and makes pollution more expensive. Which answer is strongest?',
      choices: [
        'It can raise revenue and encourage sustainability',
        'It can only raise revenue',
        'It can only reduce imports',
      ],
      prompt: 'Explain why one tax can have more than one effect.',
      visual: photos.pollution,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Who should pay?',
      question: 'If the government needs more revenue for hospitals, should it raise income tax, VAT, corporation tax or a tax on unhealthy products?',
      zh: '如果政府需要更多收入来资助医院，应该提高所得税、增值税、公司税，还是对不健康产品征税？',
      visual: photos.healthcare,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Income and wealth',
      question: 'Should higher-income households pay a higher percentage of their income in tax?',
      zh: '高收入家庭是否应该缴纳更高比例的收入作为税？',
      visual: photos.taxForms,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Direct tax',
      term:    'direct tax',
      definition: 'A direct tax is a tax on income, profit or wealth, paid directly by the taxpayer to the government.',
      examples: ['income tax on wages', 'corporation tax on company profits', 'property tax on land or buildings'],
      visual: photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'At the checkout',
      question: 'Is a tax added to prices fair if poorer households spend most of their income?',
      zh: '如果较贫困家庭会花掉大部分收入，加在价格上的税公平吗？',
      visual: photos.shopping,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Indirect tax',
      term:    'indirect tax',
      definition: 'An indirect tax is a tax on spending. It is added to the price of goods or services and collected by the seller for the government.',
      examples: ['VAT on many goods and services', 'sales tax at a shop checkout', 'indirect tax on petrol or cigarettes'],
      visual: photos.shopping,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'indirectTaxSim',
      eyebrow: 'Explore',
      title:   'Why indirect taxes can be regressive',
      taxRate: 10,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇬🇧',
          country: 'United Kingdom',
          fact: 'After the UK sugar levy, sugar in taxed soft drinks fell 46% from 2015 to 2020.',
          zh: '英国含糖饮料税后，被征税软饮料含糖量在2015至2020年下降46%。',
          source: 'Source: HM Treasury and HMRC.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China has no national sugar-sweetened beverage excise tax in the World Bank database.',
          zh: '世界银行数据库显示，中国全国层面的含糖饮料消费税为0。',
          source: 'Source: World Bank Global SSB Tax Database.',
        },
      },
      visual: factPhotos.ukSugar,
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Two direct taxes',
      leftTitle: 'Income tax',
      left: [
        'tax on wages, salaries or other personal income',
        'often progressive: higher earners may pay a higher percentage'
      ],
      rightTitle: 'Corporation tax',
      right: [
        'tax on company profits',
      ],
      prompt: 'Real-world link: the UK, US, China and many other countries use both taxes.',
      visual: photos.industry,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Taxing company profits',
      question: 'If corporation tax rises, what might a firm do with prices, wages, investment or dividends?',
      zh: '如果公司税上升，企业可能会如何调整价格、工资、投资或股息？',
      visual: photos.industry,
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'VAT, sales tax and other indirect taxes',
      leftTitle: 'VAT or sales tax',
      left: [
        'indirect tax on spending',
        'charged as a percentage of the selling price',
        'real examples: VAT in the UK and EU; sales tax in many US states'
      ],
      rightTitle: 'Indirect tax on specific goods',
      right: [
        'indirect tax on specific goods',
        'often used on cigarettes, alcohol and fuel',
        'aims can include revenue and reducing demerit goods'
      ],
      visual: photos.tobacco,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Taxing harmful goods',
      question: 'Why might governments tax cigarettes more heavily than bread?',
      zh: '为什么政府可能对香烟征收比面包更高的税？',
      visual: photos.tobacco,
    },
    {
      type: 'flow',
      eyebrow: 'Example',
      title:   'Indirect tax on tobacco',
      question: 'Many governments put high indirect taxes on cigarettes.',
      nodes: [['tax per packet rises', 'retail price rises', 'some smokers buy fewer cigarettes', 'health costs may fall']],
      footer: 'Limitation: addiction can make demand price inelastic, so quantity may fall only slightly.',
      visual: photos.tobacco,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Import tariff',
      term:    'tariff',
      definition: 'A tariff is an indirect tax on imported goods. It raises the price of imports and may protect domestic producers.',
      examples: ['tax on imported cars', 'import duty on steel', 'tariff on imported clothing'],
      visual: photos.port,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'At the port',
      question: 'If a tariff makes imported phones more expensive, who might gain and who might lose?',
      zh: '如果关税使进口手机更贵，谁可能受益，谁可能受损？',
      visual: photos.port,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇸🇪',
          country: 'Sweden',
          fact: 'Sweden’s carbon tax started at SEK 250 per tonne of fossil CO2 (about RMB 180) in 1991.',
          zh: '1991年，瑞典碳税为每吨化石二氧化碳250瑞典克朗（约180元人民币）。',
          source: 'Source: Government Offices of Sweden; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China’s national carbon market started in 2021, covering over 4.5 billion tonnes of CO2.',
          zh: '中国全国碳市场2021年启动，覆盖超过45亿吨二氧化碳排放。',
          source: 'Source: Gov.cn and MEE reporting.',
        },
      },
      visual: factPhotos.swedenCarbon,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'The smoke stack',
      question: 'Should a factory pay tax for pollution if it provides jobs in the local area?',
      zh: '如果工厂为当地提供就业，它还应该为污染纳税吗？',
      visual: photos.pollution,
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Progressive and regressive taxes',
      leftTitle: 'Progressive tax',
      left: [
        'takes a higher proportion of income as income rises',
        'example: income tax with higher rates for higher income bands',
        'often used to reduce inequality'
      ],
      rightTitle: 'Regressive tax',
      right: [
        'takes a higher proportion of income from lower-income households',
        'example: indirect tax (sales tax)',
        'may increase inequality'
      ],
      visual: photos.shopping,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'taxSim',
      eyebrow: 'Explore',
      title:   'Progressive or regressive?',
      defaultMode: 'progressive',
    },
    {
      type: 'chinaIncomeTaxSim',
      eyebrow: 'Example',
      title:   'Mainland China income tax',
      defaultIncome: 240000,
      standardDeduction: 60000,
      presets: [96000, 180000, 360000, 720000, 1200000],
      source: 'Resident comprehensive income; simplified classroom estimate. Sources: STA Individual Income Tax Law; PwC Worldwide Tax Summaries.',
    },
    {
      type: 'flow',
      eyebrow: 'Example',
      title:   'Why a sales tax can be regressive',
      question: 'Two households both pay $500 sales tax in a year.',
      nodes: [['low income: $10,000', '$500 is 5% of income', 'high income: $100,000', '$500 is 0.5% of income']],
      footer: 'The same tax payment is a larger proportion of the poorer household income.',
      visual: photos.shopping,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Proportional tax',
      term:    'proportional tax',
      definition: 'A proportional tax takes the same percentage of income from all taxpayers, even though higher earners pay more money in total.',
      examples: ['10% of $20,000 = $2,000', '10% of $80,000 = $8,000', 'same percentage, different amount'],
      visual: photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title:   'Classify the tax',
      question: 'A government charges a percentage tax on company profits and uses the revenue to fund schools.',
      choices: [
        'Direct tax and corporation tax',
        'Indirect tax on spending',
        'Tariff and regressive tax',
      ],
      prompt: 'Add one possible effect on firms.',
      visual: photos.industry,
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title:   'Pick the best explanation',
      question: 'Why might a government increase tax on petrol?',
      choices: [
        'To raise revenue and discourage pollution from car use',
        'To make exports cheaper',
        'To increase disposable income',
      ],
      prompt: 'Now add one limitation of the policy.',
      visual: photos.pollution,
    },
    {
      type: 'answer',
      eyebrow: 'Exit ticket',
      title:   'Four blanks',
      steps: [
        ['1', 'A direct tax is paid on income, profit or __________.'],
        ['2', 'An indirect tax is paid when goods and services are __________.'],
        ['3', 'A tariff is a tax on __________.'],
        ['4', 'A progressive tax takes a higher __________ as income rises.'],
      ],
      cue: 'Answer before moving from taxation to wider fiscal policy.',
      visual: photos.classroom,
      partialReview: ['.steps > .step', '.prompt'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Direct or indirect?',
      leftTitle:  'Direct tax',
      left:  ['on income or wealth', 'paid directly to government'],
      rightTitle: 'Indirect tax',
      right: ['on spending', 'paid when goods or services are bought'],
      prompt: 'Classify: income tax, VAT, corporation tax, tariff.',
      visual: photos.taxForms,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Progressive or regressive?',
      leftTitle:  'Progressive',
      left:  ['higher proportion as income rises'],
      rightTitle: 'Regressive',
      right: ['higher proportion for lower-income groups'],
      visual: photos.socialSecurity,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Reducing inequality',
      question: 'Which tax structure reduces inequality more directly?',
      zh: '哪种税收结构更直接地减少不平等？',
      visual: photos.socialSecurity,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Proportional tax',
      term:    'proportional tax',
      definition: 'A tax that takes the same proportion of income at all income levels.',
      examples: ['15% of $20,000', '15% of $80,000'],
      visual:  photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'cards',
      eyebrow: 'Exam practice',
      title:   'Classify before explaining',
      lead:    'A strong answer names the tax type, then links it to a macroeconomic aim.',
      cards: [
        ['Direct or indirect?', 'what is being taxed? income, wealth, or spending?'],
        ['Progressive?', 'does the proportion rise as income rises?'],
        ['Regressive?', 'does the proportion hit lower-income households harder?'],
        ['Proportional?', 'is the same percentage charged at all income levels?'],
      ],
      visual: photos.taxForms,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Exam practice',
      title:   'Regressive taxes',
      question: 'Why might a sales tax be called regressive?',
      zh: '为什么销售税可能被称为累退税？',
      visual: photos.shopping,
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Fiscal policy',
      subtitle: 'Changes in spending and taxation are used to influence macroeconomic aims.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Changing the economy',
      question: 'Can a government change the whole economy by changing spending and taxes?',
      zh: '政府能通过改变支出和税收来影响整个经济吗？',
      visual: photos.budgetMeeting,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Fiscal policy',
      term:    'fiscal policy',
      definition: 'The use of government spending and taxation to influence economic activity and achieve macroeconomic aims.',
      examples: ['government spending', 'taxation', 'macroeconomic aims'],
      visual: photos.budgetMeeting,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'The two fiscal-policy measures',
      leftTitle:  'Government spending',
      left:  ['increase spending to raise demand or improve supply', 'reduce spending to lower demand or borrowing'],
      rightTitle: 'Taxation',
      right: ['cut taxes to raise disposable income or incentives', 'raise taxes to reduce demand or fund spending'],
      prompt: 'Every fiscal-policy answer should mention spending and/or taxation.',
      visual: photos.budgetMeeting,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇸🇬',
          country: 'Singapore',
          fact: 'Singapore added S$1.9 billion (about RMB 10 billion) for cost-of-living relief in Budget 2024.',
          zh: '新加坡2024年预算案增加19亿新元（约100亿元人民币）缓解生活成本压力。',
          source: 'Source: Singapore Ministry of Finance; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          fact: 'China planned RMB 28.5 trillion in general public budget spending for 2024.',
          zh: '中国2024年一般公共预算支出安排28.5万亿元人民币。',
          source: 'Source: 2024 Government Work Report.',
        },
      },
      visual: factPhotos.singaporeBudget,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Stimulus',
      question: 'When unemployment is high, should the government cut taxes or increase spending?',
      zh: '当失业率较高时，政府应该减税还是增加支出？',
      visual: photos.roadwork,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Expansionary policy',
      nodes: [['higher spending or lower taxes', 'total demand rises', 'firms may increase output', 'growth and employment may rise']],
      footer: 'Risk: inflation and imports may rise.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Cooling demand',
      question: 'When prices are rising too quickly, should the government raise taxes or cut spending?',
      zh: '当价格上涨过快时，政府应该增税还是削减支出？',
      visual: photos.inflation,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Contractionary policy',
      nodes: [['lower spending or higher taxes', 'total demand falls', 'spending pressure eases', 'inflationary pressure may fall']],
      footer: 'Risk: output and employment may fall.',
      visual: photos.taxForms,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Policy conflicts',
      question: 'Which macroeconomic aim is most likely to conflict with lower inflation?',
      zh: '哪个宏观经济目标最可能与降低通货膨胀发生冲突？',
      visual: photos.budgetMeeting,
    },
    {
      type: 'cards',
      eyebrow: 'Learn',
      title:   'Fiscal policy and macro aims',
      lead:    'Each aim needs a clear spending or tax chain.',
      cards: [
        ['Growth', 'raise demand or improve supply'],
        ['Employment', 'increase demand for labour'],
        ['Price stability', 'reduce inflation pressure'],
        ['Redistribution', 'reduce income inequality'],
        ['Balance of payments', 'reduce imports'],
        ['Sustainability', 'change environmental incentives'],
      ],
      footer: 'Evaluation: identify a possible conflict or time lag.',
      visual: photos.budgetMeeting,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Economic growth',
      nodes: [['higher spending or lower taxes', 'total demand rises', 'firms produce more', 'real GDP may rise']],
      footer: 'Risk: inflation or imports may also rise.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Employment',
      nodes: [['higher demand for goods', 'firms increase output', 'firms hire more workers', 'unemployment may fall']],
      footer: 'Risk: this may be slow if workers lack the right skills.',
      visual: photos.industry,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Price stability',
      nodes: [['higher taxes or lower spending', 'total demand falls', 'spending pressure eases', 'inflation may fall']],
      footer: 'Risk: output and employment may fall.',
      visual: photos.inflation,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Redistribution',
      nodes: [['progressive taxes', 'revenue funds welfare', 'poorer households receive support', 'inequality may fall']],
      footer: 'Risk: high tax rates may reduce incentives for some workers or firms.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Balance of payments',
      nodes: [['higher taxes', 'consumer spending falls', 'imports may fall', 'current account may improve']],
      footer: 'Risk: lower demand can also reduce economic growth.',
      visual: photos.port,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Sustainability',
      nodes: [['green taxes or spending', 'incentives change', 'pollution may fall', 'sustainability may improve']],
      footer: 'Risk: firms may pass higher costs to consumers.',
      visual: photos.pollution,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'exam',
      eyebrow: 'Exam practice',
      title:   'Explain chain',
      question: 'Explain how an increase in government spending on infrastructure may help economic growth.',
      keywords: ['infrastructure', 'costs', 'investment', 'real GDP'],
      prompt:   'Write one clear chain and use "may".',
      visual:   photos.roadwork,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'exam',
      eyebrow: 'Exam practice',
      title:   'Discuss two sides',
      question: 'Discuss whether cutting taxes is the best way for a government to reduce unemployment.',
      keywords: ['disposable income', 'total demand', 'employment', 'inflation', 'budget deficit'],
      prompt:   'Build one argument for, one against, then make a judgement.',
      visual:   photos.shopping,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'answer',
      eyebrow: 'Exit ticket',
      title:   'Three blanks',
      steps: [
        ['1', 'Fiscal policy uses government __________ and taxation.'],
        ['2', 'A budget deficit means spending is __________ revenue.'],
        ['3', 'Higher taxes may reduce __________-pull inflation.'],
      ],
      cue: 'Answer before leaving.',
      visual: photos.classroom,
      partialReview: ['.steps > .step', '.prompt'],
    },
  ],
};
