/* ============================================================
   Lesson 4.2 - Fiscal policy
   Cambridge IGCSE Economics 0455 - Unit 4: Government and the macroeconomy

   Syllabus source:
   ../../../references/igcse-economics-syllabus-2027-2029.md

   Pacing note:
   Keep each slide to one teaching move and tie each policy effect back to
   the macroeconomic aims taught in 4.1.1.
   ============================================================ */

window.IGCSE = window.IGCSE || {};

const localPhoto = (file, alt, credit) => ({
  type: 'photo',
  src: `../../../assets/images/fiscal-policy/${file}`,
  alt,
  credit,
});

const photos = {
  budgetMeeting: localPhoto(
    'budget-meeting-with-congress.jpg',
    'Government officials seated around a table during budget negotiations.',
    'Wikimedia Commons / Robert McNeely'
  ),
  budgetHearing: localPhoto(
    'house-budget-committee-meeting-2020-01-15.jpg',
    'A legislative budget committee meeting in progress.',
    'Wikimedia Commons / House Budget Committee Democrats'
  ),
  classroom: localPhoto(
    'students-in-a-classroom.jpg',
    'Students working at desks in a classroom.',
    'Wikimedia Commons / Ente75'
  ),
  healthcare: localPhoto(
    'doctors-and-nurses-at-the-3rd-field-hospital.jpg',
    'Doctors and nurses standing together in a hospital.',
    'Wikimedia Commons / Defense VI Records Center'
  ),
  defence: localPhoto(
    'defence-officials-meeting.jpg',
    'Defence officials seated for a formal bilateral meeting.',
    'Wikimedia Commons / U.S. Secretary of Defense'
  ),
  roadwork: localPhoto(
    'going-to-the-sun-road-paving.jpg',
    'A road construction crew paving a mountain road.',
    'Wikimedia Commons / U.S. Dept. of Transportation'
  ),
  industry: localPhoto(
    'national-semiconductor-factory.jpg',
    'The exterior of a semiconductor factory.',
    'Wikimedia Commons / william craig'
  ),
  socialSecurity: localPhoto(
    'signing-of-the-social-security-act.jpg',
    'President Roosevelt signing the Social Security Act.',
    'Wikimedia Commons / National Archives'
  ),
  shopping: localPhoto(
    'shopping-carts-in-a-grocery-store.jpg',
    'Rows of shopping carts inside a grocery store.',
    'Wikimedia Commons / Visitor7'
  ),
  taxForms: localPhoto(
    'tax-forms.jpg',
    'Printed tax forms laid out on a table.',
    'Wikimedia Commons / Kalamazoo Public Library'
  ),
  tobacco: localPhoto(
    'tobacco-cigarette-pack.jpg',
    'A cigarette pack photographed on a table.',
    'Wikimedia Commons / Lindsay Fox'
  ),
  pollution: localPhoto(
    'smokestack-in-detroit.jpg',
    'A smokestack rising from an industrial plant.',
    'Wikimedia Commons / Gyre'
  ),
  port: localPhoto(
    'cargo-containers.jpg',
    'Stacks of cargo containers at a waterfront port.',
    'Wikimedia Commons / Roy Luck'
  ),
  inflation: localPhoto(
    'meat-inflation-in-the-united-states.jpg',
    'A grocery shelf with posted meat prices.',
    'Wikimedia Commons / Wikideas1'
  ),
};

IGCSE.lesson = {
  meta: {
    code:         '4.2',
    unit:         'Unit 4 - Government and the macroeconomy',
    title:        'Fiscal policy - Cambridge IGCSE Economics 0455',
    lessonLabel:  'Fiscal policy',
    courseLabel:  'Cambridge IGCSE Economics 0455',
  },

  slides: [
    {
      type: 'hero',
      eyebrow:  'Cambridge IGCSE Economics 0455',
      title:    'Fiscal policy',
      subtitle: 'Government spending and taxation',
      kicker:   'How can a budget help meet macroeconomic aims?',
    },
    {
      type: 'outcomes',
      eyebrow: 'Lesson objectives',
      title:   'By the end, you can',
      bullets: [
        'Explain government budgets, deficits and surpluses, including calculations.',
        'Describe main areas of government spending and reasons for taxation.',
        'Classify tax types and explain fiscal policy measures.',
        'Analyse how fiscal policy may affect growth, employment, price stability, redistribution, the balance of payments and sustainability.',
      ],
      footer: 'Success looks like: accurate term, clear policy chain, relevant macroeconomic aim, balanced evaluation.',
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'roadmap',
      eyebrow: 'Lesson map',
      title:   'Today\'s route',
      items: [
        ['4.2.1', 'Budget', 'revenue, expenditure, deficit, surplus'],
        ['4.2.2', 'Spending', 'main areas, reasons and effects'],
        ['4.2.3', 'Taxation', 'reasons and types of taxes'],
        ['4.2.4-4.2.6', 'Fiscal policy', 'measures and effects on macro aims'],
      ],
      visual: photos.budgetHearing,
    },
    {
      type: 'quiz',
      eyebrow: 'Opening dilemma',
      title:   'You control the budget',
      question: 'Growth is slowing, unemployment is rising, prices are still increasing, and pollution is high. What should the government prioritise?',
      choices: [
        'Economic growth',
        'Low unemployment',
        'Low inflation',
        'Environmental sustainability',
      ],
      prompt: 'Choose one aim, then name the likely trade-off.',
      visual: photos.budgetMeeting,
      partialReview: ['.choices > .choice', '.prompt'],
    },

    {
      type: 'section',
      eyebrow: '4.2.1',
      title:   'Government budget',
      subtitle: 'Revenue and expenditure decide whether there is a deficit or surplus.',
    },
    {
      type: 'term',
      eyebrow: 'Government budget',
      title:   'Budget balance',
      term:    'government budget',
      definition: 'A government budget is a plan for government revenue and government expenditure.',
      formula: 'Budget balance = government revenue - government expenditure',
      examples: ['negative balance = deficit', 'positive balance = surplus'],
      visual:  photos.budgetMeeting,
      partialReview: ['.termBox', '.formula', '.choices > .choice'],
    },
    {
      type: 'quiz',
      eyebrow: 'Budget calculation',
      title:   'Deficit or surplus?',
      question: 'Government revenue = $420m. Government expenditure = $510m.',
      choices: ['$90m surplus', '$90m deficit', '$930m deficit'],
      prompt:  'Calculate revenue - expenditure.',
      visual:  photos.taxForms,
    },
    {
      type: 'answer',
      eyebrow: 'Budget calculation',
      title:   'Answer',
      answer:  '$90m deficit',
      body:    '$420m - $510m = -$90m. A deficit occurs because spending is greater than revenue.',
      visual:  photos.budgetMeeting,
      partialReview: ['.answerBox'],
    },
    {
      type: 'compare',
      eyebrow: 'Budget balance',
      title:   'Deficit or surplus?',
      leftTitle:  'Budget deficit',
      left:  ['government spending exceeds government revenue', 'may require borrowing'],
      rightTitle: 'Budget surplus',
      right: ['government revenue exceeds government spending', 'may reduce borrowing or debt'],
      prompt: 'A balanced budget means revenue equals expenditure.',
      visual: photos.budgetHearing,
      partialReview: ['.splitCols > .card', '.prompt'],
    },

    {
      type: 'section',
      eyebrow: '4.2.2',
      title:   'Government spending',
      subtitle: 'Main areas of spending have different macroeconomic effects.',
    },
    {
      type: 'cards',
      eyebrow: 'Government spending',
      title:   'Main areas of spending',
      lead:    'These are common areas. The next slides explain why governments spend in them.',
      cards: [
        ['Education', 'schools, colleges and training'],
        ['Healthcare', 'hospitals, doctors and public health'],
        ['Infrastructure', 'roads, rail, ports and digital networks'],
        ['Welfare', 'benefits, pensions and income support'],
        ['Defence', 'armed forces and national security'],
        ['Industry support', 'subsidies, grants and research support'],
      ],
      visual: photos.budgetHearing,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'cards',
      eyebrow: 'Government spending',
      title:   'Why governments spend',
      lead:    'Use one clear reason at a time in an exam answer.',
      cards: [
        ['Provide merit goods', 'education and healthcare', '1'],
        ['Provide public goods', 'defence and street lighting', '2'],
        ['Invest in infrastructure', 'roads, rail and ports', '3'],
        ['Support key industries', 'subsidies and R&D', '4'],
        ['Reduce inequality', 'benefits and pensions', '5'],
        ['Manage the macroeconomy', 'influence demand and inflation', '6'],
      ],
      visual: photos.budgetHearing,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for spending',
      title:   '1. Provide merit goods',
      question: 'Education and healthcare may be underprovided if people have to pay the full price.',
      nodes: [['government funds schools or hospitals', 'more people can access them', 'skills and health improve', 'productivity may rise']],
      footer: 'Exam link: merit goods can improve living standards and long-run growth.',
      visual: photos.classroom,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for spending',
      title:   '2. Provide public goods',
      question: 'Some goods would not be provided by private firms because people can benefit without paying directly.',
      nodes: [['government funds defence', 'the country is protected', 'people and firms face less risk', 'economic activity is protected']],
      footer: 'Exam link: public goods create benefits that markets may not provide.',
      visual: photos.defence,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for spending',
      title:   '3. Invest in infrastructure',
      nodes: [['more infrastructure spending', 'lower transport costs', 'firms may produce more', 'real GDP may rise']],
      footer: 'This links spending to economic growth.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Quick check',
      title:   'Which reason?',
      question: 'The government builds a new railway between factories and a port. Which reason for spending is most direct?',
      choices: [
        'Provide a public good',
        'Invest in infrastructure',
        'Reduce inequality',
      ],
      prompt: 'Say the answer, then add one likely effect on firms.',
      visual: photos.roadwork,
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for spending',
      title:   '4. Support key industries',
      question: 'Governments may support industries that are important for jobs, exports or future technology.',
      nodes: [['subsidy for a key industry', 'firms face lower costs', 'investment or R&D may rise', 'competitiveness may improve']],
      footer: 'Evaluation: subsidies have an opportunity cost and may protect inefficient firms.',
      visual: photos.industry,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for spending',
      title:   '5. Reduce inequality',
      nodes: [['higher welfare spending', 'poorer households receive support', 'income inequality may fall']],
      footer: 'Add a cost: the government may need higher taxes or borrowing.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for spending',
      title:   '6. Manage the macroeconomy',
      question: 'Government spending can be changed to influence total demand.',
      nodes: [['higher government spending', 'total demand rises', 'firms may increase output', 'growth and employment may rise']],
      footer: 'Evaluation: demand may rise too much and create inflationary pressure.',
      visual: photos.budgetMeeting,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Quick check',
      title:   'Spot the reason',
      question: 'The government increases unemployment benefits during a downturn. Which reason fits best?',
      choices: [
        'Reduce inequality',
        'Support key industries',
        'Provide public goods',
      ],
      prompt: 'Now name one possible opportunity cost.',
      visual: photos.socialSecurity,
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Spending challenge',
      title:   'Match policy to aim',
      question: 'Which spending decision most directly supports environmental sustainability?',
      choices: [
        'Build cleaner public transport',
        'Increase debt-interest payments',
        'Cut education spending',
      ],
      prompt: 'Now add one possible opportunity cost.',
      visual: photos.pollution,
      partialReview: ['.choices > .choice', '.prompt'],
    },

    {
      type: 'section',
      eyebrow: '4.2.3',
      title:   'Taxation',
      subtitle: 'Taxes raise revenue, change behaviour and influence demand.',
    },
    {
      type: 'quiz',
      eyebrow: 'Taxation',
      title:   'Why tax?',
      question: 'Which reason for taxation is shown by a tariff on imported cars?',
      choices: [
        'Reduce imports',
        'Raise revenue',
        'Redistribute income',
        'Encourage sustainability',
      ],
      prompt: 'There may be more than one valid answer.',
      visual: photos.port,
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'cards',
      eyebrow: 'Taxation',
      title:   'Reasons for taxation',
      lead:    'A tax can have more than one purpose, but exam answers should focus on one clear reason at a time.',
      cards: [
        ['Raise revenue', 'fund government spending', '1'],
        ['Reduce demerit goods', 'reduce harmful consumption', '2'],
        ['Reduce imports', 'make imports more expensive', '3'],
        ['Redistribute income', 'reduce income inequality', '4'],
        ['Influence demand', 'change total spending', '5'],
        ['Encourage sustainability', 'change environmental incentives', '6'],
      ],
      visual:  photos.pollution,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for taxation',
      title:   '1. Raise revenue',
      nodes: [['government charges taxes', 'revenue rises', 'public services can be funded']],
      footer: 'Example: income tax can help fund education and healthcare.',
      visual: photos.taxForms,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for taxation',
      title:   '2. Reduce demerit goods',
      nodes: [['tax on cigarettes', 'price rises', 'quantity demanded may fall', 'health costs may fall']],
      footer: 'Evaluation: demand may be price inelastic.',
      visual: photos.tobacco,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for taxation',
      title:   '3. Reduce imports',
      nodes: [['tariff on imports', 'import prices rise', 'consumers may buy fewer imports', 'domestic firms may sell more']],
      footer: 'Evaluation: other countries may retaliate.',
      visual: photos.port,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Quick check',
      title:   'Which reason?',
      question: 'A government increases tax on alcohol. Which reason for taxation is most direct?',
      choices: [
        'Raise revenue only',
        'Reduce consumption of a demerit good',
        'Reduce imports',
      ],
      prompt: 'Add one reason why the effect may be limited.',
      visual: photos.tobacco,
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for taxation',
      title:   '4. Redistribute income',
      nodes: [['higher taxes on high incomes', 'government revenue rises', 'welfare can be funded', 'inequality may fall']],
      footer: 'Progressive taxes are usually linked most directly to redistribution.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for taxation',
      title:   '5. Influence demand',
      nodes: [['higher income tax', 'disposable income falls', 'consumer spending may fall', 'inflationary pressure may fall']],
      footer: 'This may conflict with growth and employment.',
      visual: photos.inflation,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Reason for taxation',
      title:   '6. Encourage sustainability',
      nodes: [['pollution tax', 'firms face higher costs for polluting', 'cleaner methods become more attractive']],
      footer: 'Evaluate: firms may pass higher costs to consumers.',
      visual: photos.pollution,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Quick check',
      title:   'One tax, two possible aims',
      question: 'A pollution tax raises money and makes pollution more expensive. Which answer is strongest?',
      choices: [
        'It can raise revenue and encourage sustainability',
        'It can only raise revenue',
        'It can only reduce imports',
      ],
      prompt: 'Explain why one tax can have more than one effect.',
      visual: photos.pollution,
      partialReview: ['.choices > .choice', '.prompt'],
    },
    {
      type: 'compare',
      eyebrow: 'Tax types',
      title:   'Direct or indirect?',
      leftTitle:  'Direct tax',
      left:  ['on income or wealth', 'paid directly to government'],
      rightTitle: 'Indirect tax',
      right: ['on spending', 'paid when goods or services are bought'],
      prompt: 'Classify: income tax, VAT, corporation tax, tariff.',
      visual: photos.taxForms,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'compare',
      eyebrow: 'Tax types',
      title:   'Progressive or regressive?',
      leftTitle:  'Progressive',
      left:  ['higher proportion as income rises'],
      rightTitle: 'Regressive',
      right: ['higher proportion for lower-income groups'],
      prompt: 'Which type reduces inequality more directly?',
      visual: photos.socialSecurity,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'term',
      eyebrow: 'Tax types',
      title:   'Proportional tax',
      term:    'proportional tax',
      definition: 'A tax that takes the same proportion of income at all income levels.',
      examples: ['15% of $20,000', '15% of $80,000'],
      visual:  photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'cards',
      eyebrow: 'Exam trap',
      title:   'Classify before explaining',
      lead:    'A strong answer names the tax type, then links it to a macroeconomic aim.',
      cards: [
        ['Direct or indirect?', 'what is being taxed? income, wealth, or spending?'],
        ['Progressive?', 'does the proportion rise as income rises?'],
        ['Regressive?', 'does the proportion hit lower-income households harder?'],
        ['Proportional?', 'is the same percentage charged at all income levels?'],
      ],
      footer: 'Why might a sales tax be called regressive?',
      visual: photos.taxForms,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },

    {
      type: 'section',
      eyebrow: '4.2.4-4.2.6',
      title:   'Fiscal policy',
      subtitle: 'Changes in spending and taxation are used to influence macroeconomic aims.',
    },
    {
      type: 'term',
      eyebrow: 'Key term',
      title:   'Fiscal policy',
      term:    'fiscal policy',
      definition: 'The use of government spending and taxation to influence economic activity and achieve macroeconomic aims.',
      examples: ['government spending', 'taxation', 'macroeconomic aims'],
      visual: photos.budgetMeeting,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'compare',
      eyebrow: 'Fiscal measures',
      title:   'The two fiscal-policy measures',
      leftTitle:  'Government spending',
      left:  ['increase spending to raise demand or improve supply', 'reduce spending to lower demand or borrowing'],
      rightTitle: 'Taxation',
      right: ['cut taxes to raise disposable income or incentives', 'raise taxes to reduce demand or fund spending'],
      prompt: 'Every fiscal-policy answer should mention spending and/or taxation.',
      visual: photos.budgetMeeting,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy',
      title:   'Expansionary policy',
      nodes: [['higher spending or lower taxes', 'total demand rises', 'firms may increase output', 'growth and employment may rise']],
      footer: 'Risk: inflation and imports may rise.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy',
      title:   'Contractionary policy',
      nodes: [['lower spending or higher taxes', 'total demand falls', 'spending pressure eases', 'inflationary pressure may fall']],
      footer: 'Risk: output and employment may fall.',
      visual: photos.taxForms,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'cards',
      eyebrow: 'Fiscal policy effects',
      title:   'Fiscal policy and macro aims',
      lead:    'Each aim needs a clear spending or tax chain.',
      cards: [
        ['Growth', 'raise demand or improve supply'],
        ['Employment', 'increase demand for labour'],
        ['Price stability', 'reduce inflation pressure'],
        ['Redistribution', 'reduce income inequality'],
        ['Balance of payments', 'reduce imports'],
        ['Sustainability', 'change environmental incentives'],
      ],
      footer: 'Evaluation: identify a possible conflict or time lag.',
      visual: photos.budgetMeeting,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy effects',
      title:   'Economic growth',
      nodes: [['higher spending or lower taxes', 'total demand rises', 'firms produce more', 'real GDP may rise']],
      footer: 'Risk: inflation or imports may also rise.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy effects',
      title:   'Employment',
      nodes: [['higher demand for goods', 'firms increase output', 'firms hire more workers', 'unemployment may fall']],
      footer: 'Risk: this may be slow if workers lack the right skills.',
      visual: photos.industry,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy effects',
      title:   'Price stability',
      nodes: [['higher taxes or lower spending', 'total demand falls', 'spending pressure eases', 'inflation may fall']],
      footer: 'Risk: output and employment may fall.',
      visual: photos.inflation,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy effects',
      title:   'Redistribution',
      nodes: [['progressive taxes', 'revenue funds welfare', 'poorer households receive support', 'inequality may fall']],
      footer: 'Risk: high tax rates may reduce incentives for some workers or firms.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy effects',
      title:   'Balance of payments',
      nodes: [['higher taxes', 'consumer spending falls', 'imports may fall', 'current account may improve']],
      footer: 'Risk: lower demand can also reduce economic growth.',
      visual: photos.port,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Fiscal policy effects',
      title:   'Sustainability',
      nodes: [['green taxes or spending', 'incentives change', 'pollution may fall', 'sustainability may improve']],
      footer: 'Risk: firms may pass higher costs to consumers.',
      visual: photos.pollution,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'exam',
      eyebrow: 'Exam practice',
      title:   'Explain chain',
      question: 'Explain how an increase in government spending on infrastructure may help economic growth.',
      keywords: ['infrastructure', 'costs', 'investment', 'real GDP'],
      prompt:   'Write one clear chain and use "may".',
      visual:   photos.roadwork,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'exam',
      eyebrow: 'Evaluation practice',
      title:   'Discuss two sides',
      question: 'Discuss whether cutting taxes is the best way for a government to reduce unemployment.',
      keywords: ['disposable income', 'total demand', 'employment', 'inflation', 'budget deficit'],
      prompt:   'Build one argument for, one against, then make a judgement.',
      visual:   photos.shopping,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'answer',
      eyebrow: 'Exit check',
      title:   'Three blanks',
      steps: [
        ['1', 'Fiscal policy uses government __________ and taxation.'],
        ['2', 'A budget deficit means spending is __________ revenue.'],
        ['3', 'Higher taxes may reduce __________-pull inflation.'],
      ],
      cue: 'Answer before leaving.',
      visual: photos.classroom,
      partialReview: ['.steps > .step', '.prompt'],
    },
  ],
};
