window.IGCSE = window.IGCSE || {};

IGCSE.quiz = {
  id: '4-3-fiscal-policy',
  version: '1.0.0',
  title: 'Fiscal policy quiz',
  description: 'Check the main fiscal policy concepts from this deck.',
  questions: [
    {
      id: 'definition',
      type: 'multipleChoice',
      prompt: 'Fiscal policy mainly uses which two tools?',
      choices: ['Government spending and taxation', 'Exchange rates and tariffs', 'Wages and rent', 'Profit and dividends'],
      answer: 0,
      explanation: 'Fiscal policy is based on government spending and taxation.',
    },
    {
      id: 'taxation',
      type: 'fillBlank',
      prompt: 'A government can raise revenue by increasing __________.',
      acceptedAnswers: ['taxation', 'taxes', 'tax'],
      explanation: 'Taxes are a major source of government revenue.',
    },
    {
      id: 'deficit',
      type: 'multipleChoice',
      prompt: 'What happens when government spending is greater than government revenue?',
      choices: ['Budget deficit', 'Budget surplus', 'Trade surplus', 'Full employment'],
      answer: 0,
      explanation: 'A deficit occurs when expenditure exceeds revenue.',
    },
    {
      id: 'surplus',
      type: 'fillBlank',
      prompt: 'When government revenue is greater than expenditure, there is a budget __________.',
      acceptedAnswers: ['surplus'],
      explanation: 'A surplus is a positive budget balance.',
    },
    {
      id: 'expansionary',
      type: 'multipleChoice',
      prompt: 'Which measure is most likely to increase aggregate demand?',
      choices: ['Increasing government spending', 'Cutting public services', 'Raising income tax', 'Reducing welfare payments'],
      answer: 0,
      explanation: 'Higher government spending is an injection into aggregate demand.',
    },
    {
      id: 'inflation',
      type: 'fillBlank',
      prompt: 'If fiscal policy raises aggregate demand too much, it may cause demand-pull __________.',
      acceptedAnswers: ['inflation'],
      explanation: 'Demand-pull inflation can occur when demand grows faster than supply.',
    },
    {
      id: 'redistribution',
      type: 'multipleChoice',
      prompt: 'Which policy is most directly linked to redistributing income?',
      choices: ['Progressive taxes and welfare payments', 'Removing all taxes', 'Reducing public education', 'Cutting healthcare spending'],
      answer: 0,
      explanation: 'Progressive taxation and transfer payments can reduce income inequality.',
    },
    {
      id: 'employment',
      type: 'fillBlank',
      prompt: 'Higher government spending may reduce unemployment by increasing demand for __________.',
      acceptedAnswers: ['labour', 'labor', 'workers'],
      explanation: 'Higher output can increase derived demand for workers.',
    },
  ],
};
