window.IGCSE = window.IGCSE || {};

IGCSE.quiz = {
  id: '2-8-market-failure',
  version: '1.1.0',
  title: 'Market failure and arguments against markets quiz',
  description: 'Check your understanding of disadvantages of market economies and causes of market failure.',
  questions: [
    {
      id: 'market-failure-definition',
      type: 'multipleChoice',
      prompt: 'What is market failure?',
      choices: [
        'An inefficient allocation of resources by the market.',
        'Any fall in a firm’s profit.',
        'A market where prices never change.',
        'A situation where consumers have too much choice.',
      ],
      answer: 0,
      explanation: 'Market failure means the free market does not allocate resources in the best way for society.',
    },
    {
      id: 'external-cost-scenario',
      type: 'multipleChoice',
      prompt: 'A factory sells a product cheaply, but nearby residents suffer dirty air and health costs. What is the best explanation?',
      choices: [
        'There is an external cost, so social cost is greater than private cost.',
        'There is an external benefit, so social benefit is greater than private benefit.',
        'It is a public good because non-payers can benefit.',
        'It is consumer sovereignty because consumers choose the product.',
      ],
      answer: 0,
      explanation: 'Pollution imposes costs on third parties, so the market may produce too much.',
    },
    {
      id: 'social-cost',
      type: 'fillBlank',
      prompt: 'Social cost equals private cost plus external __________.',
      acceptedAnswers: ['cost', 'costs'],
      explanation: 'External costs are added to private costs to find social cost.',
    },
    {
      id: 'public-good-free-rider',
      type: 'multipleChoice',
      prompt: 'Why might a private firm not provide street lighting?',
      choices: [
        'People can benefit even if they do not pay, so private revenue may not cover cost.',
        'Street lighting always has high private profit.',
        'Street lighting is a demerit good that consumers overuse.',
        'Competition always guarantees public goods.',
      ],
      answer: 0,
      explanation: 'The free-rider problem means public goods may not be provided by the free market.',
    },
    {
      id: 'merit-good',
      type: 'multipleChoice',
      prompt: 'Why might education be under-consumed in a market economy?',
      choices: [
        'Consumers may underestimate its long-term private and social benefits.',
        'Education always creates external costs.',
        'Education is always a demerit good.',
        'Private firms never respond to demand.',
      ],
      answer: 0,
      explanation: 'Merit goods may be under-consumed when consumers underestimate benefits or cannot afford enough.',
    },
    {
      id: 'demerit-good',
      type: 'multipleChoice',
      prompt: 'Which chain best explains over-consumption of a demerit good?',
      choices: [
        'Consumers underestimate costs -> demand is too high -> the good is over-consumed.',
        'Consumers cannot be excluded -> firms cannot charge -> the good is not provided.',
        'External benefits are ignored -> demand is too low -> the good is under-consumed.',
        'Competition rises -> output is restricted -> prices rise.',
      ],
      answer: 0,
      explanation: 'Demerit goods such as cigarettes or sugary drinks may be over-consumed in a free market.',
    },
    {
      id: 'inequality',
      type: 'multipleChoice',
      prompt: 'Why can a market economy increase inequality?',
      choices: [
        'Firms respond to profitable demand, and richer consumers have more spending power.',
        'All consumers always have equal income.',
        'The price mechanism guarantees equal access to every good.',
        'Competition removes all differences in wages.',
      ],
      answer: 0,
      explanation: 'Market demand reflects ability to pay as well as wants, so poorer households may have less access.',
    },
    {
      id: 'monopoly-power',
      type: 'multipleChoice',
      prompt: 'What is a likely problem when one firm dominates a market?',
      choices: [
        'Competition falls, so output may be restricted and prices may be higher.',
        'Consumer choice always increases.',
        'External costs automatically disappear.',
        'All public goods become profitable.',
      ],
      answer: 0,
      explanation: 'Monopoly power weakens competitive pressure and can harm consumers.',
    },
  ],
};
